Use parcinfo;
#CREATE TABLE SALLE( nSalle VARCHAR(20) PRIMARY KEY, nbPoste NUMERIC,indIP VARCHAR(11) REFERENCES SEGMENT (indIP));
#CREATE TABLE POSTE (nPoste VARCHAR(7) PRIMARY KEY, nomPoste VARCHAR(20), indIP VARCHAR(11) REFERENCES SEGMENT (indIP), ad VARCHAR(3), typePoste VARCHAR(9),nSalle VARCHAR(20) REFERENCES SALLE (nSalle));
#CREATE TABLE LOGICIEL( nLog VARCHAR(20) PRIMARY KEY, nomLog VARCHAR (20) , dateAch dateTIME , aversion VARCHAR(7),typeLog VARCHAR(9),prix DECIMAL(6,2));
#cREATE TABLE INSTALLER( nPoste VARCHAR(7) REFERENCES POSTE (nPoste) , nLog VARCHAR (20) REFERENCES LOGICIEL (nLog), numIns NUMERIC PRIMARY KEY, dateIns dateTIME, delai NUMERIC);
#CREATE TABLE TYPES ( typeLP VARCHAR(9) PRIMARY KEY, nnomType VARCHAR(20) );
INSERT INTO SEGMENT (indIP, nomSegment) VALUES ("130.120.80","Brin RDC");
